package xmart.com.xmart_android.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.google.gson.Gson;

/**
 * Entity mapped to table "CART_ITEM".
 */
public class CartItem {

    private String Id;
    private String ProductId;
    private String ProductName;
    private String ShopName;
    private String UnitsName;
    private String Price;
    private String Quantity;
    private String Amount;
    private String Image;
    private String showEditQuantity;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CartItem() {
    }

    public CartItem(String Id) {
        this.Id = Id;
    }

    public CartItem(String Id, String ProductId, String ProductName, String ShopName, String UnitsName, String Price, String Quantity, String Amount, String showEditQuantity) {
        this.Id = Id;
        this.ProductId = ProductId;
        this.ProductName = ProductName;
        this.ShopName = ShopName;
        this.UnitsName = UnitsName;
        this.Price = Price;
        this.Quantity = Quantity;
        this.Amount = Amount;
        this.showEditQuantity = showEditQuantity;
    }

    public String getImage() {
        return Image;
    }

    public void setImage(String image) {
        Image = image;
    }

    public String getId() {
        return Id;
    }

    public void setId(String Id) {
        this.Id = Id;
    }

    public String getProductId() {
        return ProductId;
    }

    public void setProductId(String ProductId) {
        this.ProductId = ProductId;
    }

    public String getProductName() {
        return ProductName;
    }

    public void setProductName(String ProductName) {
        this.ProductName = ProductName;
    }

    public String getShopName() {
        return ShopName;
    }

    public void setShopName(String ShopName) {
        this.ShopName = ShopName;
    }

    public String getUnitsName() {
        return UnitsName;
    }

    public void setUnitsName(String UnitsName) {
        this.UnitsName = UnitsName;
    }

    public String getPrice() {
        return Price;
    }

    public void setPrice(String Price) {
        this.Price = Price;
    }

    public String getQuantity() {
        return Quantity;
    }

    public void setQuantity(String Quantity) {
        this.Quantity = Quantity;
    }

    public String getAmount() {
        return Amount;
    }

    public void setAmount(String Amount) {
        this.Amount = Amount;
    }

    public String getShowEditQuantity() {
        return showEditQuantity;
    }

    public void setShowEditQuantity(String showEditQuantity) {
        this.showEditQuantity = showEditQuantity;
    }

    // KEEP METHODS - put your custom methods here
    public String objectToJson(CartItem doiTuong) {
        Gson gson = new Gson();
        String json = gson.toJson(doiTuong);
        return json;
    }

    public CartItem jsonToObject(String json) {
        Gson gson = new Gson();
        return gson.fromJson(json,CartItem.class);
    }

    public  CartItem[] jsonToArrayObject(String json) {
        Gson gson = new Gson();
        return gson.fromJson(json,  CartItem[].class);
    }
    // KEEP METHODS END

}
