package xmart.com.xmart_android.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CATEGORIES".
 */
public class Categories {

    private String Id;
    private String Name;
    private String Desc;
    private String Image;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Categories() {
    }

    public Categories(String Id) {
        this.Id = Id;
    }

    public Categories(String Id, String Name, String Desc, String Image) {
        this.Id = Id;
        this.Name = Name;
        this.Desc = Desc;
        this.Image = Image;
    }

    public String getId() {
        return Id;
    }

    public void setId(String Id) {
        this.Id = Id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getDesc() {
        return Desc;
    }

    public void setDesc(String Desc) {
        this.Desc = Desc;
    }

    public String getImage() {
        return Image;
    }

    public void setImage(String Image) {
        this.Image = Image;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
