package xmart.com.xmart_android.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        NguoiDungDao.createTable(db, ifNotExists);
        OrderDao.createTable(db, ifNotExists);
        ProcessDao.createTable(db, ifNotExists);
        CancelDao.createTable(db, ifNotExists);
        CompleteDao.createTable(db, ifNotExists);
        CartItemDao.createTable(db, ifNotExists);
        InfoDao.createTable(db, ifNotExists);
        CategoriesDao.createTable(db, ifNotExists);
        ProductNewDao.createTable(db, ifNotExists);
        OwnerDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        NguoiDungDao.dropTable(db, ifExists);
        OrderDao.dropTable(db, ifExists);
        ProcessDao.dropTable(db, ifExists);
        CancelDao.dropTable(db, ifExists);
        CompleteDao.dropTable(db, ifExists);
        CartItemDao.dropTable(db, ifExists);
        InfoDao.dropTable(db, ifExists);
        CategoriesDao.dropTable(db, ifExists);
        ProductNewDao.dropTable(db, ifExists);
        OwnerDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(NguoiDungDao.class);
        registerDaoClass(OrderDao.class);
        registerDaoClass(ProcessDao.class);
        registerDaoClass(CancelDao.class);
        registerDaoClass(CompleteDao.class);
        registerDaoClass(CartItemDao.class);
        registerDaoClass(InfoDao.class);
        registerDaoClass(CategoriesDao.class);
        registerDaoClass(ProductNewDao.class);
        registerDaoClass(OwnerDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
