package xmart.com.xmart_android.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "INFO".
 */
public class Info {

    private String Id;
    private String Type;
    private String User;
    private String Token;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Info() {
    }

    public Info(String Id) {
        this.Id = Id;
    }

    public Info(String Id, String Type, String User, String Token) {
        this.Id = Id;
        this.Type = Type;
        this.User = User;
        this.Token = Token;
    }

    public String getId() {
        return Id;
    }

    public void setId(String Id) {
        this.Id = Id;
    }

    public String getType() {
        return Type;
    }

    public void setType(String Type) {
        this.Type = Type;
    }

    public String getUser() {
        return User;
    }

    public void setUser(String User) {
        this.User = User;
    }

    public String getToken() {
        return Token;
    }

    public void setToken(String Token) {
        this.Token = Token;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
