package xmart.com.xmart_android.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.google.gson.Gson;

/**
 * Entity mapped to table "NGUOI_DUNG".
 */
public class NguoiDung {

    private String Id;
    private String UserName;
    private String Token;
    private String FirstName;
    private String LastName;
    private String PhoneNumber;
    private String Birthday;
    private String Gender;
    private String Image;
    private String HomeAddr;
    private String HomeLatitude;
    private String HomeLongitude;
    private String WorkAddr;
    private String WorkLatitude;
    private String WorkLongitude;
    private String Point;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public NguoiDung() {
    }

    public NguoiDung(String Id) {
        this.Id = Id;
    }

    public NguoiDung(String Id, String UserName, String Token, String FirstName, String LastName, String PhoneNumber, String Birthday, String Gender, String Image, String HomeAddr, String HomeLatitude, String HomeLongitude, String WorkAddr, String WorkLatitude, String WorkLongitude, String Point) {
        this.Id = Id;
        this.UserName = UserName;
        this.Token = Token;
        this.FirstName = FirstName;
        this.LastName = LastName;
        this.PhoneNumber = PhoneNumber;
        this.Birthday = Birthday;
        this.Gender = Gender;
        this.Image = Image;
        this.HomeAddr = HomeAddr;
        this.HomeLatitude = HomeLatitude;
        this.HomeLongitude = HomeLongitude;
        this.WorkAddr = WorkAddr;
        this.WorkLatitude = WorkLatitude;
        this.WorkLongitude = WorkLongitude;
        this.Point = Point;
    }

    public String getId() {
        return Id;
    }

    public void setId(String Id) {
        this.Id = Id;
    }

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    public String getToken() {
        return Token;
    }

    public void setToken(String Token) {
        this.Token = Token;
    }

    public String getFirstName() {
        return FirstName;
    }

    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    public String getLastName() {
        return LastName;
    }

    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    public String getPhoneNumber() {
        return PhoneNumber;
    }

    public void setPhoneNumber(String PhoneNumber) {
        this.PhoneNumber = PhoneNumber;
    }

    public String getBirthday() {
        return Birthday;
    }

    public void setBirthday(String Birthday) {
        this.Birthday = Birthday;
    }

    public String getGender() {
        return Gender;
    }

    public void setGender(String Gender) {
        this.Gender = Gender;
    }

    public String getImage() {
        return Image;
    }

    public void setImage(String Image) {
        this.Image = Image;
    }

    public String getHomeAddr() {
        return HomeAddr;
    }

    public void setHomeAddr(String HomeAddr) {
        this.HomeAddr = HomeAddr;
    }

    public String getHomeLatitude() {
        return HomeLatitude;
    }

    public void setHomeLatitude(String HomeLatitude) {
        this.HomeLatitude = HomeLatitude;
    }

    public String getHomeLongitude() {
        return HomeLongitude;
    }

    public void setHomeLongitude(String HomeLongitude) {
        this.HomeLongitude = HomeLongitude;
    }

    public String getWorkAddr() {
        return WorkAddr;
    }

    public void setWorkAddr(String WorkAddr) {
        this.WorkAddr = WorkAddr;
    }

    public String getWorkLatitude() {
        return WorkLatitude;
    }

    public void setWorkLatitude(String WorkLatitude) {
        this.WorkLatitude = WorkLatitude;
    }

    public String getWorkLongitude() {
        return WorkLongitude;
    }

    public void setWorkLongitude(String WorkLongitude) {
        this.WorkLongitude = WorkLongitude;
    }

    public String getPoint() {
        return Point;
    }

    public void setPoint(String Point) {
        this.Point = Point;
    }

    // KEEP METHODS - put your custom methods here
    public String objectToJson(NguoiDung doiTuong) {
        Gson gson = new Gson();
        String json = gson.toJson(doiTuong);
        return json;
    }

    public NguoiDung jsonToObject(String json) {
        Gson gson = new Gson();
        return gson.fromJson(json,NguoiDung.class);
    }

    public  NguoiDung[] jsonToArrayObject(String json) {
        Gson gson = new Gson();
        return gson.fromJson(json,  NguoiDung[].class);
    }
    // KEEP METHODS END

}
