package xmart.com.xmart_android.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.io.Serializable;

/**
 * Entity mapped to table "ORDER_OWNER".
 */
public class OrderOwner implements Serializable {

    private String Id;
    private String UserId;
    private String OwnerId ;
    private String Total;
    private String Status;
    private String LastName;
    private String PhoneNumber ;
    private String HomeAddr;
    private String WorkAddr;
    private String Gender;
    private String FirstName ;
    private String Ordered;
    private String Processed ;
    private String Canceled;
    private String Completed;
    private String ShopName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public OrderOwner() {
    }

    public OrderOwner(String Id) {
        this.Id = Id;
    }

    public OrderOwner(String Id, String UserId, String OwnerId , String Total, String Status, String LastName, String PhoneNumber , String HomeAddr, String WorkAddr, String Gender, String FirstName , String Ordered, String Processed , String Canceled, String Completed, String ShopName) {
        this.Id = Id;
        this.UserId = UserId;
        this.OwnerId  = OwnerId ;
        this.Total = Total;
        this.Status = Status;
        this.LastName = LastName;
        this.PhoneNumber  = PhoneNumber ;
        this.HomeAddr = HomeAddr;
        this.WorkAddr = WorkAddr;
        this.Gender = Gender;
        this.FirstName  = FirstName ;
        this.Ordered = Ordered;
        this.Processed  = Processed ;
        this.Canceled = Canceled;
        this.Completed = Completed;
        this.ShopName = ShopName;
    }

    public String getId() {
        return Id;
    }

    public void setId(String Id) {
        this.Id = Id;
    }

    public String getUserId() {
        return UserId;
    }

    public void setUserId(String UserId) {
        this.UserId = UserId;
    }

    public String getOwnerId () {
        return OwnerId ;
    }

    public void setOwnerId (String OwnerId ) {
        this.OwnerId  = OwnerId ;
    }

    public String getTotal() {
        return Total;
    }

    public void setTotal(String Total) {
        this.Total = Total;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public String getLastName() {
        return LastName;
    }

    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    public String getPhoneNumber () {
        return PhoneNumber ;
    }

    public void setPhoneNumber (String PhoneNumber ) {
        this.PhoneNumber  = PhoneNumber ;
    }

    public String getHomeAddr() {
        return HomeAddr;
    }

    public void setHomeAddr(String HomeAddr) {
        this.HomeAddr = HomeAddr;
    }

    public String getWorkAddr() {
        return WorkAddr;
    }

    public void setWorkAddr(String WorkAddr) {
        this.WorkAddr = WorkAddr;
    }

    public String getGender() {
        return Gender;
    }

    public void setGender(String Gender) {
        this.Gender = Gender;
    }

    public String getFirstName () {
        return FirstName ;
    }

    public void setFirstName (String FirstName ) {
        this.FirstName  = FirstName ;
    }

    public String getOrdered() {
        return Ordered;
    }

    public void setOrdered(String Ordered) {
        this.Ordered = Ordered;
    }

    public String getProcessed () {
        return Processed ;
    }

    public void setProcessed (String Processed ) {
        this.Processed  = Processed ;
    }

    public String getCanceled() {
        return Canceled;
    }

    public void setCanceled(String Canceled) {
        this.Canceled = Canceled;
    }

    public String getCompleted() {
        return Completed;
    }

    public void setCompleted(String Completed) {
        this.Completed = Completed;
    }

    public String getShopName() {
        return ShopName;
    }

    public void setShopName(String ShopName) {
        this.ShopName = ShopName;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
