package xmart.com.xmart_android.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.google.gson.Gson;

/**
 * Entity mapped to table "ORDER".
 */
public class Order {

    private String Id;
    private String UserId;
    private String OwnerId;
    private String Total;
    private String Status;
    private String Ordered;
    private String Processed;
    private String Cancelled;
    private String Completed;
    private String ShopName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Order() {
    }

    public Order(String Id) {
        this.Id = Id;
    }

    public Order(String Id, String UserId, String OwnerId, String Total, String Status, String Ordered, String Processed, String Cancelled, String Completed, String ShopName) {
        this.Id = Id;
        this.UserId = UserId;
        this.OwnerId = OwnerId;
        this.Total = Total;
        this.Status = Status;
        this.Ordered = Ordered;
        this.Processed = Processed;
        this.Cancelled = Cancelled;
        this.Completed = Completed;
        this.ShopName = ShopName;
    }

    public String getId() {
        return Id;
    }

    public void setId(String Id) {
        this.Id = Id;
    }

    public String getUserId() {
        return UserId;
    }

    public void setUserId(String UserId) {
        this.UserId = UserId;
    }

    public String getOwnerId() {
        return OwnerId;
    }

    public void setOwnerId(String OwnerId) {
        this.OwnerId = OwnerId;
    }

    public String getTotal() {
        return Total;
    }

    public void setTotal(String Total) {
        this.Total = Total;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public String getOrdered() {
        return Ordered;
    }

    public void setOrdered(String Ordered) {
        this.Ordered = Ordered;
    }

    public String getProcessed() {
        return Processed;
    }

    public void setProcessed(String Processed) {
        this.Processed = Processed;
    }

    public String getCancelled() {
        return Cancelled;
    }

    public void setCancelled(String Cancelled) {
        this.Cancelled = Cancelled;
    }

    public String getCompleted() {
        return Completed;
    }

    public void setCompleted(String Completed) {
        this.Completed = Completed;
    }

    public String getShopName() {
        return ShopName;
    }

    public void setShopName(String ShopName) {
        this.ShopName = ShopName;
    }

    // KEEP METHODS - put your custom methods here
    public String objectToJson(Order doiTuong) {
        Gson gson = new Gson();
        String json = gson.toJson(doiTuong);
        return json;
    }

    public Order jsonToObject(String json) {
        Gson gson = new Gson();
        return gson.fromJson(json,Order.class);
    }

    public  Order[] jsonToArrayObject(String json) {
        Gson gson = new Gson();
        return gson.fromJson(json,  Order[].class);
    }
    // KEEP METHODS END

}
